### ISSUE TITLE
Migration error on update 1.2.1 > 1.2.2

### ISSUE THREAD

**Issue by stevehurst** [nfourtythree/craft3-entriessubset#15]
I'm getting this migration error on plugin update. Running Craft 3.4.23.

```
yii\base\ErrorException: Invalid argument supplied for foreach()

Migration: nfourtythree\entriessubset\migrations\m190906_102859_entry_type_id_to_uid

Output:

Exception: Invalid argument supplied for foreach() (/Users/stevehurst/Sites/kalypso.craft.local/vendor/nfourtythree/entriessubset/src/migrations/m190906_102859_entry_type_id_to_uid.php:60)
#0 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/Users/stevehur...', 60)
#1 /Users/stevehurst/Sites/kalypso.craft.local/vendor/nfourtythree/entriessubset/src/migrations/m190906_102859_entry_type_id_to_uid.php(60): craft\web\ErrorHandler->handleError(2, 'Invalid argumen...', '/Users/stevehur...', 60, Array)
#2 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/db/Migration.php(52): nfourtythree\entriessubset\migrations\m190906_102859_entry_type_id_to_uid->safeUp()
#3 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(nfourtythree\entriessubset\migrations\m190906_102859_entry_type_id_to_uid))
#5 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#6 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#7 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#9 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#12 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#13 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#14 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#15 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#16 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/stevehurst/Sites/kalypso.craft.local/public/index.php(21): yii\base\Application->run()
#18 {main}
```

**Comment by stevehurst** [comment]
I am still getting migration errors on updating this module. Please advise.
